name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
  create-release:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/pfrp2040-build:latest
    needs: build-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: ./configs/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rp2040-firmware
          path: "./"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./firmware.uf2,./update.bin"
          bodyFile: "CHANGELOG.md"
